### PR TITLE
Fix invalid ArrayBuffer -> Number cast

### LINKED ISSUE #77: from input file with  error("Offset 0 hasn't been loaded yet")
hello,
i'm try to get from input file with function, but i'm getting error ""Offset 0 hasn't been loaded yet"

html colde: 
`<input type="file" id="file" onchange="loadFile(this)">`

java script code:
```
function loadFile(input) {
      var myfile = input.files[0],
     console.log(myfile);
       jsmediatags.read(myfile, {
          onSuccess: function(tag) {
          console.log(tag);
            },
               onError: function(error) {
                   console.log(error);
            }
                });
  }

```
Please help
Yasin

### PR DESCRIPTION
**Pull request by chrisparton1991**
Fixes #77.

I ran `npm test` before my changes and got 7 failing tests. I'm not sure if it's because I'm running on Windows?

I also ran Flow after my change and got a warning, but I've never used Flow and don't know how to fix that one.

### CODE REVIEW

**Comment by aadsm** [comment]
Can you paste the failures you got?

**Comment by chrisparton1991** [comment]
Sure thing, here are the errors:
[flow-failures.txt](https://github.com/aadsm/jsmediatags/files/1403474/flow-failures.txt)
[test-failures.txt](https://github.com/aadsm/jsmediatags/files/1403478/test-failures.txt)

I'm running Windows 10.0.15063, Node 8.4.0 and NPM 5.4.2.

**Comment by aadsm** [comment]
@chrisparton1991, I’ve fixed both tests and flow and pushed them to master so it should be fine now, thanks for warning (I should really setup travis).
There’s only one thing missing now, can you add a test that catches the bug you fix to avoid having regressions in the future?

**Comment by chrisparton1991** [comment]
Thanks for getting that stuff fixed up! I can run all of the tests without issue now.

The unit tests already appear to be catching the issue. With my fix they all pass, without the fix I get:
```
 FAIL  src\__tests__\BlobFileReader-test.js
  ● BlobFileReader › should read a byte

    Offset 0 hasn't been loaded yet.
```

**Comment by MartinDawson** [comment]
@aadsm Can this be merged please? Thanks for fixing @chrisparton1991.

**Comment by chrisparton1991** [comment]
No problem @MartinDawson, glad I could help!

**Comment by MartinDawson** [comment]
hehe, very helpful indeed as it was causi... ALL GLORY TO THE HYPNOTOAD!

**Comment by aadsm** [comment]
Awesome, thank you so much for fixing this!

**Comment by chrisparton1991** [comment]
No problem, thanks for making an awesome library :)

I'm using jsmediatags in my LED sequencer project (https://github.com/chrisparton1991/sparkled), it's been super useful.

**Comment by aadsm** [comment]
good to hear! that project looks pretty cool :)

**Pull request merged**
